language: java
sudo: false
jdk:
- openjdk11
install: true
script: mvn install -B
notifications:
  irc:
    channels:
      # "irc.rizon.net#runelite"
      - secure: "ZMch8HHC93gYhggtIbgSU/bGn5VKzKnJ2pOQDWpWwlRKADUq3YXL3j/TKGWM4pywztJ6UFOJQtRiHPg0jkk1XUNa16qWdkclq+a/ocOOAVeaFR/HNw7JgLaj4ymTv2PWmrR2qjoMwwUtbON8Cqc3J9BoO5Vut0mZXuOflSjoNVcKmhxBQ2A3tjvhAIQ2bp3JhSA5jP9sJ4VXdqHG6ZcIlXh1iaAL5J7cC+C1uIROflQTQ9aNMHg/Czg4lChIdK9C1dAf1YrM3eIwbmB4UTH8GnYD+txWEKXk80oilH3tfSN/7vDopuSiODAxI4FH7L/JB0u4/5rKuyMwua5GcGNxYm20EiVoB8QUNaUbOqjxTzNsKHAYl98JzYUcbWSs+xleRpUwZE5WXhMJhTAsZIW2CMAevqnaneUNblU8aNvgDqEbLLa8uP5N/ZMTMMCkHc01Y9y91PhHnAd5mD3UJkzeJaSXPuAz6+TCgjXGYCRYamyUkW7dlBOxVCWPEMdvTod+INTxUvEQH6TRUfQOYUnsMvCXyFDVrQ6WbJw1z18xiaINwsybmsYRdlCbSq2TJxlfzHiUaTrkkY2/8YK4wxWjqkiTnbUSIXU5oQnjQOUcJYlDtYyuOmXiDuONJXf6HIfnLz9sOiBPIn7FyvqowaqR+IfZWTXGX6Z5HTdQYOwNTqY="
